site_name: OPNsense app for Splunk
edit_uri: ""
repo_url: https://github.com/ZachChristensen28/Opnsense_App_for_Splunk
repo_name: ZachChristensen28/Opnsense_App_for_Splunk

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - search

markdown_extensions:
  - toc:
      permalink: true
  - attr_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite

theme:
  name: material
  logo: images/opn_app_logo.png
  favicon: images/opn_app_logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    # - header.autohide
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    # - toc.integrate
    - navigation.tracking
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/zachthesplunker/
    - icon: fontawesome/brands/github
      link: https://github.com/ZachChristensen28
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ZachTheSplunker

nav:
  - Home: index.md
  - Getting Started:
      - App Dependencies: getting-started/app-dependencies.md
      - Where to Install: getting-started/where-to-install.md
      - Configure:
          - Setup Data Model Acceleration: getting-started/configure/configure-dma.md
          - Update Macros: getting-started/configure/configure-macros.md
  - Reference:
      - Search Macros: reference/reference-macros.md
      - Scheduled Searches: reference/reference-searches.md
      - Changelog:
          - Release Notes: reference/releases/index.md
          - Release History: reference/releases/release-history.md
